### ISSUE TITLE
Path Export Error

### ISSUE THREAD

**Issue by jdjohnson1085** [anasrar/Blender-UE4-Workspace#13]
![image](https://user-images.githubusercontent.com/68668835/88237662-50e1b380-cc45-11ea-9f6d-ce036a028168.png)

I get this error when exporting to UE4 but not FBX.

**Comment by anasrar** [comment]
on temporary folder make sure it's absolute path folder
![image](https://user-images.githubusercontent.com/38805204/88241269-d4d28480-ccb3-11ea-9904-6fdf46dc50b0.png)
https://github.com/anasrar/Blender-UE4-Workspace#usage
