### ISSUE TITLE
import assets: error when try to update list when project file is to big

### ISSUE THREAD

**Issue by anasrar** [anasrar/Blender-UE4-Workspace#18]
basically `remote_execute.py` does not support many output character from unreal engine console

I'm think to store assets list in a single file

**Comment by anasrar** [comment]
NOT TESTED YET FOR BLENDER IN WINDOWS

**Comment by dandezign** [comment]
your fix works I can Import all the assets from my big project.

**Comment by anasrar** [comment]
> your fix works I can Import all the assets from my big project.

can you tell me what OS you using (windows / linux) and what blender type you using (installer / portable) ??

**Comment by dandezign** [comment]
Im using windows

**Comment by dandezign** [comment]
> > your fix works I can Import all the assets from my big project.
> 
> can you tell me what OS you using (windows / linux) and what blender type you using (installer / portable) ??

I'm using windows 10 pro and using portable version of blender

**Comment by anasrar** [comment]
> > > your fix works I can Import all the assets from my big project.
> > 
> > 
> > can you tell me what OS you using (windows / linux) and what blender type you using (installer / portable) ??
> 
> I'm using windows 10 pro and using portable version of blender

thanks for your information, i need to test on installer version but too busy with my side project

**Comment by dandezign** [comment]
> > > > your fix works I can Import all the assets from my big project.
> > > 
> > > 
> > > can you tell me what OS you using (windows / linux) and what blender type you using (installer / portable) ??
> > 
> > 
> > I'm using windows 10 pro and using portable version of blender
> 
> thanks for your information, i need to test on installer version but too busy with my side project

I'll test on the installed version as soon as i can

**Comment by dandezign** [comment]
I can confirm it works on the installed version of blender.

**Comment by anasrar** [comment]
@dandezign thanks for helping me test
