### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by gerroon** [anasrar/Blender-UE4-Workspace#23]
Hi

I installed the addon in 2.91 (Windows) and trying to use it with Unreal 4.26 (Windows) but this is what I am getting when I connect to Unreal and when I try to update the asset list  in Blender

Unreal has Python installed and remote execution is enabled in the project.

```

location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\UE4Workspace\UE4WS_ExportOptionImportAssets.py", line 159, in execute
    AssetsList += json.loads(output["output"][0]["output"])
IndexError: list index out of range

location: <unknown location>:-1

```

**Comment by anasrar** [comment]
hey sorry for late response.
the issues is already fix in #18.

you can download v.2.0 alpha version : https://github.com/anasrar/Blender-UE4-Workspace/releases/tag/v2.0.0

**Comment by gerroon** [comment]
Thanks I will give it a try

**Comment by anasrar** [comment]
I will close this issue soon
