### ISSUE TITLE
If the Export Folder starts with `//`, an error will occur during export.

### ISSUE THREAD

**Issue by aoisensi** [anasrar/Blender-UE4-Workspace#25]
The title says it all.

**Comment by anasrar** [comment]
you need absolute path folder

**Comment by aoisensi** [comment]
If you use the Select Folder button on the right, you may get a path that starts with `//`, right?

**Comment by aoisensi** [comment]
and absolute path is based by blender.exe folder
it is useless

**Comment by anasrar** [comment]
yeah its blender bug I found since 2.81 if you dont select root storage
![image](https://user-images.githubusercontent.com/38805204/109433536-33cf5780-7a54-11eb-8ac3-a104e254ec40.png)

**Comment by aoisensi** [comment]
ohhh sorry ok
i got it
