### ISSUE TITLE
Can't update assets list

### ISSUE THREAD

**Issue by iMaciaP** [anasrar/Blender-UE4-Workspace#26]
Hi I installed blender add-on and enabled scripting and remote execution in unreal but when i press the button in blender : "Update Assets List" this error shows up and no asset is listed.

Thanks in advance.

![image](https://user-images.githubusercontent.com/47883521/112802882-0259a400-9073-11eb-96a4-562ccf0a5e6c.png)

in unreal:

![image](https://user-images.githubusercontent.com/47883521/112803248-5fedf080-9073-11eb-9e90-d01d290e899a.png)

PS: blender version: 2.90.1 unreal: 4.26.1

**Comment by anasrar** [comment]
fixed on v.2.0.0 alpha
https://github.com/anasrar/Blender-UE4-Workspace/releases/tag/v2.0.0

issues : #18

**Comment by anasrar** [comment]
Duplicate of #18

**Comment by iMaciaP** [comment]
this is the version i was using, and followed the config :/

**Comment by anasrar** [comment]
the path script on screenshot was different
on v.2.0.0 alpha is `../UE4Workspace/import_asset/main.py`

better using v.2.0.0 since Unreal Engine 4.26 is using Python 3

on previous version is write on Python 2 (Before Unreal Engine 2.26) so the `execfile` was deprecated on Python 3

**Comment by anasrar** [comment]
![image](https://user-images.githubusercontent.com/38805204/113142365-c0448400-9265-11eb-81d4-ad640151973e.png)

**Comment by anasrar** [comment]
I will close this issue soon

**Comment by iMaciaP** [comment]
Sorry for the inactivity, i was in vacation. In version 2.0.0 alpha works. Thanks for the support.

Versions:

BlenderUE4Wkspc: 2.0.0 Alpha
Blender: 2.83.0 (LTS)
Unreal: 4.26.1
