### ISSUE TITLE
Hi. I have a problem with finding the plugin in Add-ons list

### ISSUE THREAD

**Issue by 6Equinox** [anasrar/Blender-UE4-Workspace#27]
I installed the plugin, successfully.
![image](https://user-images.githubusercontent.com/84278395/118400203-30329080-b693-11eb-84d2-aea1f97ebb16.png)

and....I can find the plugin in the right root folder.
![image](https://user-images.githubusercontent.com/84278395/118400223-4f312280-b693-11eb-9c8c-775264cc1ba4.png)

But I can't find it in the Add-ons list
![image](https://user-images.githubusercontent.com/84278395/118400241-61ab5c00-b693-11eb-852e-544fd105350a.png)

My Blender version is 2.92. I downloaded it from steam. My other plugins can work normally. Thanks for your attention. I hope my bad English won't bother U...orz. Thanks a lot

**Comment by anasrar** [comment]
if you install correctly, you should have new addon category
![image](https://user-images.githubusercontent.com/38805204/118403118-de483580-b6a7-11eb-8a0e-8d86d107a09f.png)

and the folder name is UE4Workspace not Blender-UE4-Workspace.

try to download here (UE4Workspace.zip) :
https://github.com/anasrar/Blender-UE4-Workspace/releases/tag/v2.0.0
and follow this installation instruction :
https://github.com/anasrar/Blender-UE4-Workspace#installation

**Comment by 6Equinox** [comment]
It works! Thanks a lot. I think I install the wrong folder file...Anyway, thanks again!
