### ISSUE TITLE
Function issue

### ISSUE THREAD

**Issue by 6Equinox** [anasrar/Blender-UE4-Workspace#28]
Sorry to bother U again.

I need to import some static meshes from UE4 to Blender.
And I wanna know....Does Workspace have the functions that ...

1.Can the plugin import the basic texture with static mesh (I need to import a lot of meshes. The number of tex is very large)
2.Can the plugin remember the positon/rotation/scale information in UE4 level and make it in Blender scene when I import them?
3.There is a lot of assets and several levels in my UE4 project. When I connect Blender and UE4, the Asset list is very long in Workspace in blender. Can I only choose the part which only shows in my current UE4 level to show in the Asset list in Workspace？  

Thanks for the attention.

**Comment by anasrar** [comment]
1. no.
2. no, maybe  I will add this feature in near future https://github.com/anasrar/Blender-UE4-Workspace#copy-transform-to-unreal-engine-map.
3. no, for now you can not choose which folder you want to show in assets list, maybe I will add some filter folder in the future.

thanks for feedback.

**Comment by 6Equinox** [comment]
Sorry for the late reply! I seldom use github and forget to check the message. 
Besides , I think the first two functions are really useful. And I strongly advise these. 
Thanks for the answer!
