### ISSUE TITLE
It works with UE5, Great! But ,if i want to export StaticMesh with  hierarchy?

### ISSUE THREAD

**Issue by unsanedingding** [anasrar/Blender-UE4-Workspace#30]
![微信图片_20211016023857](https://user-images.githubusercontent.com/26058055/137536829-5e56dcca-2cf7-4d5b-a99d-1287402a8bf1.png)

**Comment by anasrar** [comment]
what do you mean with hierarchy ?
do you want export all child to single static mesh base on parent or export all child as single part ?

**Comment by unsanedingding** [comment]
it' ok! thanks a lot
