### ISSUE TITLE
In UE4, The x.fbx  (axisFbx)No polygon were found on mesh

### ISSUE THREAD

**Issue by unsanedingding** [anasrar/Blender-UE4-Workspace#34]
what should I do?Or use some setting?
![x](https://user-images.githubusercontent.com/26058055/143517951-316de09b-6004-4fc1-8c5b-f3adebf26a89.png)
![y](https://user-images.githubusercontent.com/26058055/143517963-472120c2-3529-47e3-82c7-8021953350e5.png)
![ue4](https://user-images.githubusercontent.com/26058055/143517969-db2205d7-9433-461e-995f-d64d29802b83.png)

**Comment by anasrar** [comment]
can you provide any information like what are you trying to do, addon and engine verison, import export setting

**Comment by unsanedingding** [comment]
thanks ,email to you.
