### ISSUE TITLE
About export fbx file (for UE4),  how to set scale(100) for all mesh?

### ISSUE THREAD

**Issue by unsanedingding** [anasrar/Blender-UE4-Workspace#35]
About export fbx file (for UE4),  how to set scale(100) for all mesh?

**Comment by anasrar** [comment]
you can set in FBX export setting

**Comment by unsanedingding** [comment]
sorry, still invalid.
I reinstall blender2.93,and download UE4_Workspace plugin, set "FBX Export Setting/Scale" to 100(other setting are default), only export blender default cube model ,then import to UE(keep scale "1" in UE import setting) a new level, .
But, the cube model still very small, why?

**Comment by unsanedingding** [comment]
oh,I think i find the bug, i must check"Apply Transform", and "Scale " setting no use(1 or 100  all is ok);
 But , i must remove remove transform(offset of mesh center) by blender's "ALT + G"; because i need mesh's center is zero.
So .... how can i get scaled mesh and have NOT "Transform" to used UE ?
